name: todo_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.5
  flutter_slidable: ^3.0.0

flutter_icons:
  android: true
  image_path: "assets/images/unnamed.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.1

  flutter_lints: ^2.0.2



flutter:

  uses-material-design: true
  assets:
    - assets/images/unnamed.png
#  fonts:
#    - family: AkayaTelivigala
#      fonts:
#        - asset: assets/AkayaTelivigala-Regular.
